import type { ConformanceSuite } from '../../../packages/tsn-testing/src/spec.js'

export const inputSuite: ConformanceSuite = {
  id: 'inputs',
  label: 'Inputs Suite',
  navLabel: 'Inputs Suite',
  navTestId: 'suite.inputs',
  navTag: 3,
  covers: ['Search', 'Input', 'TextArea', 'Select', 'Checkbox', 'Radio', 'Switch'],
  description: 'Search, text inputs, select, boolean controls, live state binding, and reset behavior.',
  artifactPrefix: 'inputs',
  cases: [
    {
      id: 'input-static',
      label: 'search, text, and boolean input primitives',
      actions: [],
      coverage: [
        { primitive: 'Search', properties: ['type', 'value', 'placeholder'], states: ['empty-default'] },
        { primitive: 'Input', properties: ['type', 'value', 'placeholder'], states: ['preset-default'] },
        { primitive: 'TextArea', properties: ['type', 'value', 'placeholder'], states: ['multiline-default'] },
        { primitive: 'Select', properties: ['value'], states: ['selected-default'] },
        { primitive: 'Checkbox', properties: ['value'], states: ['checked-default'] },
        { primitive: 'Radio', properties: ['value'], states: ['unchecked-default'] },
        { primitive: 'Switch', properties: ['value'], states: ['checked-default'] },
        { primitive: 'Text', properties: ['text'], states: ['state-mirror'] },
      ],
      expects: [
        { kind: 'property', id: 'inputs.search', prop: 'type', includes: 'NSSearchField' },
        { kind: 'property', id: 'inputs.input', prop: 'type', includes: 'NSTextField' },
        { kind: 'property', id: 'inputs.textarea', prop: 'type', includes: 'NSTextView' },
        { kind: 'property', id: 'inputs.search', prop: 'value', equals: '' },
        { kind: 'property', id: 'inputs.input', prop: 'value', equals: 'preset text' },
        { kind: 'property', id: 'inputs.textarea', prop: 'value', equals: 'line one\nline two' },
        { kind: 'property', id: 'inputs.search', prop: 'placeholder', includes: 'Search shared state' },
        { kind: 'property', id: 'inputs.input', prop: 'placeholder', includes: 'Input primitive' },
        { kind: 'property', id: 'inputs.textarea', prop: 'placeholder', includes: 'TextArea primitive' },
        { kind: 'property', id: 'inputs.select', prop: 'value', equals: 'Medium' },
        { kind: 'property', id: 'inputs.select', prop: 'value', equals: 'Medium' },
        { kind: 'property', id: 'inputs.checkbox', prop: 'value', equals: 'true' },
        { kind: 'property', id: 'inputs.radio', prop: 'value', equals: 'false' },
        { kind: 'property', id: 'inputs.switch', prop: 'value', equals: 'true' },
        { kind: 'property', id: 'inputs.query-mirror', prop: 'text', includes: 'Query: empty' },
        { kind: 'property', id: 'inputs.input-mirror', prop: 'text', includes: 'Input: preset text' },
        { kind: 'property', id: 'inputs.textarea-mirror', prop: 'text', includes: 'TextArea: line one\nline two' },
        { kind: 'property', id: 'inputs.select-mirror', prop: 'text', includes: 'Select: Medium' },
        { kind: 'property', id: 'inputs.select-mirror', prop: 'text', includes: 'Select: Medium' },
        { kind: 'property', id: 'inputs.checkbox-mirror', prop: 'text', includes: 'Checkbox: on' },
        { kind: 'property', id: 'inputs.radio-mirror', prop: 'text', includes: 'Radio: off' },
        { kind: 'property', id: 'inputs.switch-mirror', prop: 'text', includes: 'Switch: on' },
      ],
    },
    {
      id: 'search-live',
      label: 'typing into search updates shared state',
      actions: [{ kind: 'type-id', id: 'inputs.search', text: 'latency' }],
      coverage: [
        { primitive: 'Search', properties: ['value'], states: ['live-binding', 'shared-store'] },
      ],
      expects: [
        { kind: 'property', id: 'inputs.query-mirror', prop: 'text', includes: 'Query: latency' },
        { kind: 'property', id: 'shell.query', prop: 'text', includes: 'Query: latency' },
        { kind: 'property', id: 'shell.search', prop: 'value', equals: 'latency' },
      ],
    },
    {
      id: 'sidebar-search-live',
      label: 'typing into sidebar search updates input suite mirrors',
      actions: [{ kind: 'type-id', id: 'shell.search', text: 'throughput' }],
      coverage: [
        { primitive: 'Search', properties: ['value'], states: ['sidebar-origin', 'shared-store'] },
      ],
      expects: [
        { kind: 'property', id: 'shell.search', prop: 'value', equals: 'throughput' },
        { kind: 'property', id: 'inputs.search', prop: 'value', equals: 'throughput' },
        { kind: 'property', id: 'inputs.query-mirror', prop: 'text', includes: 'Query: throughput' },
      ],
    },
    {
      id: 'input-live',
      label: 'typing into input updates mirrored state',
      actions: [{ kind: 'type-id', id: 'inputs.input', text: 'ticket-42' }],
      coverage: [
        { primitive: 'Input', properties: ['value'], states: ['live-binding'] },
      ],
      expects: [
        { kind: 'property', id: 'inputs.input', prop: 'value', equals: 'ticket-42' },
        { kind: 'property', id: 'inputs.input-mirror', prop: 'text', includes: 'Input: ticket-42' },
      ],
    },
    {
      id: 'textarea-live',
      label: 'typing into textarea updates mirrored state',
      actions: [{ kind: 'type-id', id: 'inputs.textarea', text: 'draft notes' }],
      coverage: [
        { primitive: 'TextArea', properties: ['value'], states: ['live-binding', 'multiline-edit'] },
      ],
      expects: [
        { kind: 'property', id: 'inputs.textarea', prop: 'value', equals: 'draft notes' },
        { kind: 'property', id: 'inputs.textarea-mirror', prop: 'text', includes: 'TextArea: draft notes' },
      ],
    },
    {
      id: 'select-live',
      label: 'selecting an option updates mirrored state',
      actions: [{ kind: 'select-id', id: 'inputs.select', text: 'High' }],
      coverage: [
        { primitive: 'Select', properties: ['value'], states: ['live-select'] },
      ],
      expects: [
        { kind: 'property', id: 'inputs.select', prop: 'value', equals: 'High' },
        { kind: 'property', id: 'inputs.select-mirror', prop: 'text', includes: 'Select: High' },
      ],
    },
    {
      id: 'checkbox-live',
      label: 'clicking checkbox updates mirrored state',
      actions: [{ kind: 'click-id', id: 'inputs.checkbox' }],
      coverage: [
        { primitive: 'Checkbox', properties: ['value'], states: ['live-toggle'] },
      ],
      expects: [
        { kind: 'property', id: 'inputs.checkbox', prop: 'value', equals: 'false' },
        { kind: 'property', id: 'inputs.checkbox-mirror', prop: 'text', includes: 'Checkbox: off' },
      ],
    },
    {
      id: 'radio-live',
      label: 'clicking radio updates mirrored state',
      actions: [{ kind: 'click-id', id: 'inputs.radio' }],
      coverage: [
        { primitive: 'Radio', properties: ['value'], states: ['live-toggle'] },
      ],
      expects: [
        { kind: 'property', id: 'inputs.radio', prop: 'value', equals: 'true' },
        { kind: 'property', id: 'inputs.radio-mirror', prop: 'text', includes: 'Radio: on' },
      ],
    },
    {
      id: 'switch-live',
      label: 'clicking switch updates mirrored state',
      actions: [{ kind: 'click-id', id: 'inputs.switch' }],
      coverage: [
        { primitive: 'Switch', properties: ['value'], states: ['live-toggle'] },
      ],
      expects: [
        { kind: 'property', id: 'inputs.switch', prop: 'value', equals: 'false' },
        { kind: 'property', id: 'inputs.switch-mirror', prop: 'text', includes: 'Switch: off' },
      ],
    },
    {
      id: 'reset',
      label: 'reset button restores default state',
      actions: [
        { kind: 'type-id', id: 'inputs.search', text: 'latency' },
        { kind: 'type-id', id: 'inputs.input', text: 'ticket-42' },
        { kind: 'type-id', id: 'inputs.textarea', text: 'changed notes' },
        { kind: 'select-id', id: 'inputs.select', text: 'Low' },
        { kind: 'click-id', id: 'inputs.checkbox' },
        { kind: 'click-id', id: 'inputs.radio' },
        { kind: 'click-id', id: 'inputs.switch' },
        { kind: 'click-id', id: 'inputs.reset' },
      ],
      coverage: [
        { primitive: 'Search', properties: ['value'], states: ['reset'] },
        { primitive: 'Input', properties: ['value'], states: ['reset'] },
        { primitive: 'TextArea', properties: ['value'], states: ['reset'] },
        { primitive: 'Select', properties: ['value'], states: ['reset'] },
        { primitive: 'Checkbox', properties: ['value'], states: ['reset'] },
        { primitive: 'Radio', properties: ['value'], states: ['reset'] },
        { primitive: 'Switch', properties: ['value'], states: ['reset'] },
        { primitive: 'Button', properties: ['text'], states: ['reset-click'] },
      ],
      expects: [
        { kind: 'property', id: 'inputs.search', prop: 'value', equals: '' },
        { kind: 'property', id: 'inputs.input', prop: 'value', equals: 'preset text' },
        { kind: 'property', id: 'inputs.textarea', prop: 'value', equals: 'line one\nline two' },
        { kind: 'property', id: 'inputs.checkbox', prop: 'value', equals: 'true' },
        { kind: 'property', id: 'inputs.radio', prop: 'value', equals: 'false' },
        { kind: 'property', id: 'inputs.switch', prop: 'value', equals: 'true' },
        { kind: 'property', id: 'inputs.query-mirror', prop: 'text', includes: 'Query: empty' },
        { kind: 'property', id: 'inputs.input-mirror', prop: 'text', includes: 'Input: preset text' },
        { kind: 'property', id: 'inputs.textarea-mirror', prop: 'text', includes: 'TextArea: line one\nline two' },
        { kind: 'property', id: 'inputs.checkbox-mirror', prop: 'text', includes: 'Checkbox: on' },
        { kind: 'property', id: 'inputs.radio-mirror', prop: 'text', includes: 'Radio: off' },
        { kind: 'property', id: 'inputs.switch-mirror', prop: 'text', includes: 'Switch: on' },
        { kind: 'property', id: 'shell.last-action', prop: 'text', includes: 'Last action: reset' },
      ],
    },
  ],
}
