import * as ts from 'typescript'

import type { FuncSig } from '../../tsn-compiler-ui/src/types.js'
import { appendHostedAsyncHelpers } from './builtins-hosted.js'
import type { ClassDef, StructDef } from './types.js'

export interface HookProgramAdapter {
  appendGlobalDeclarations(lines: string[]): void
  hasHooks(): boolean
  appendApplyFunctions(lines: string[]): void
}

export interface ProgramAssemblyContext {
  hasJsx: boolean
  classDefs: Map<string, ClassDef>
  structs: StructDef[]
  arrayTypes: Set<string>
  promiseTypes: Map<string, string>
  needsJsonParser: boolean
  jsxGlobals: string[]
  hooks: HookProgramAdapter
  funcSigs: Map<string, FuncSig>
  lambdas: string[]
  functions: string[]
  jsxBootStmts: string[]
  sourceFile: ts.SourceFile | null
  sourceFileName: string
  genJsonParser(): string
  isSkippable(statement: ts.Statement): boolean
  tsTypeToC(typeNode: ts.TypeNode | undefined, fallback?: string): string
  inferVarType(decl: ts.VariableDeclaration): string
  inferVarTsType(decl: ts.VariableDeclaration): string
  tsTypeName(typeNode: ts.TypeNode | undefined): string
  emitObjLit(node: ts.ObjectLiteralExpression): string
  emitExpr(node: ts.Node): string
}

export function assembleProgram(
  ctx: ProgramAssemblyContext,
  sourceFiles: ts.SourceFile[],
  entryFile: ts.SourceFile,
  hasTopLevelJsx: boolean,
): string {
  const lines: string[] = []
  lines.push('/* Generated by TSN Compiler v3 */')
  lines.push('#include "runtime.h"')
  if (ctx.hasJsx) lines.push('#include "ui.h"')
  lines.push('')

  const simpleStructs: StructDef[] = []
  const complexStructs: StructDef[] = []
  for (const s of ctx.structs) {
    const needsCustomArrayType = s.fields.some(f =>
      f.cType.endsWith('Arr') &&
      f.cType !== 'StrArr' &&
      f.cType !== 'DoubleArr',
    )
    if (needsCustomArrayType) complexStructs.push(s)
    else simpleStructs.push(s)
  }

  for (const [name] of ctx.classDefs) {
    lines.push(`typedef struct ${name}_s ${name};`)
  }
  if (ctx.classDefs.size) lines.push('')

  for (const s of simpleStructs) {
    if (ctx.classDefs.has(s.name)) {
      if (s.fields.length > 0) {
        lines.push(`struct ${s.name}_s { ${s.fields.map(f => `${f.cType} ${f.name};`).join(' ')} };`)
      } else {
        lines.push(`struct ${s.name}_s { int _dummy; };`)
      }
    } else {
      lines.push(`typedef struct { ${s.fields.map(f => `${f.cType} ${f.name};`).join(' ')} } ${s.name};`)
    }
  }

  for (const t of ctx.arrayTypes) {
    if (t === 'Str' || t === 'double') continue
    lines.push(`DEFINE_ARRAY(${t}Arr, ${t})`)
  }

  for (const [name, valueCType] of ctx.promiseTypes) {
    if (valueCType === 'void') lines.push(`DEFINE_PROMISE_VOID(${name})`)
    else lines.push(`DEFINE_PROMISE(${name}, ${valueCType})`)
  }

  // Promise helpers are emitted before function bodies so any promise-returning
  // declarations can refer to them uniformly.
  //
  // Edge cases for later:
  // - ordering once async lowering emits extra state-machine structs/functions
  // - duplicate helper families for timers, fetch, and eventual stream bodies
  // - hosted-only async helper emission vs target-specific runtimes
  appendHostedAsyncHelpers(lines, ctx.promiseTypes)

  for (const s of complexStructs) {
    if (ctx.classDefs.has(s.name)) {
      lines.push(`struct ${s.name}_s { ${s.fields.map(f => `${f.cType} ${f.name};`).join(' ')} };`)
    } else {
      lines.push(`typedef struct { ${s.fields.map(f => `${f.cType} ${f.name};`).join(' ')} } ${s.name};`)
    }
  }

  if (ctx.structs.length) lines.push('')

  if (ctx.needsJsonParser) {
    lines.push(ctx.genJsonParser())
    lines.push('')
  }

  if (ctx.jsxGlobals.length) {
    for (const g of ctx.jsxGlobals) lines.push(g)
    lines.push('')
  }

  ctx.hooks.appendGlobalDeclarations(lines)

  for (const [name, sig] of ctx.funcSigs) {
    if (name === 'main') continue
    const fixType = (t: string) => (t.startsWith('struct ') ? t.replace('struct ', '') : t)
    const ps = sig.params.map(p => `${fixType(p.cType)} ${p.name}`).join(', ') || 'void'
    lines.push(`${fixType(sig.returnCType)} ${name}(${ps});`)
  }
  if (ctx.funcSigs.size) lines.push('')

  if (ctx.hasJsx && ctx.hooks.hasHooks()) ctx.hooks.appendApplyFunctions(lines)

  for (const l of ctx.lambdas) {
    lines.push(l)
    lines.push('')
  }

  for (const f of ctx.functions) {
    lines.push(f.includes('void main(') ? f.replace('void main(void)', 'void ts_main(void)') : f)
    lines.push('')
  }

  if (ctx.hasJsx && hasTopLevelJsx) {
    lines.push('int main(int argc, char **argv) {')
    lines.push('    ts_install_crash_handler(argv[0]);')
    for (const s of ctx.jsxBootStmts) lines.push(s)
    lines.push('    UIHandle _jsx_root = _ts_render_root();')
    lines.push('    if (_jsx_root) ui_run(_jsx_root);')
    lines.push('    return 0;')
    lines.push('}')
    return lines.join('\n')
  }

  if (ctx.funcSigs.has('main')) {
    const mainSig = ctx.funcSigs.get('main')
    const initLines: string[] = []
    for (const sf of sourceFiles) {
      if (sf === entryFile) continue
      ctx.sourceFile = sf
      ctx.sourceFileName = sf.fileName
      for (const s of sf.statements) {
        if (!ts.isVariableStatement(s) || ctx.isSkippable(s)) continue
        for (const d of s.declarationList.declarations) {
          if (d.initializer && ts.isIdentifier(d.name)) {
            const name = d.name.getText()
            const cType = d.type ? ctx.tsTypeToC(d.type) : ctx.inferVarType(d)
            const val = ts.isObjectLiteralExpression(d.initializer)
              ? `(${cType})${ctx.emitObjLit(d.initializer)}`
              : ctx.emitExpr(d.initializer)
            initLines.push(`    ${name} = ${val};`)
          }
        }
      }
    }

    ctx.sourceFile = entryFile
    ctx.sourceFileName = entryFile.fileName
    for (const s of entryFile.statements) {
      if (!ts.isVariableStatement(s) || ctx.isSkippable(s)) continue
      for (const d of s.declarationList.declarations) {
        if (d.initializer && ts.isIdentifier(d.name)) {
          const name = d.name.getText()
          const cType = d.type ? ctx.tsTypeToC(d.type) : ctx.inferVarType(d)
          const val = ts.isObjectLiteralExpression(d.initializer)
            ? `(${cType})${ctx.emitObjLit(d.initializer)}`
            : ctx.emitExpr(d.initializer)
          initLines.push(`    ${name} = ${val};`)
        }
      }
    }

    if (initLines.length > 0) {
      lines.push(`static void _ts_init_globals(void) {\n${initLines.join('\n')}\n}`)
      lines.push('')
    }

    lines.push('int main(int argc, char **argv) {')
    lines.push('    ts_install_crash_handler(argv[0]);')
    if (initLines.length > 0) lines.push('    _ts_init_globals();')
    if (mainSig?.returnType.startsWith('Promise<')) {
      const mainReturnCType = mainSig.returnCType.startsWith('struct ')
        ? mainSig.returnCType.replace('struct ', '')
        : mainSig.returnCType
      lines.push(`    ${mainReturnCType} _main_result = ts_main();`)
      if (mainSig.returnType === 'Promise<void>') {
        lines.push(`    TS_AWAIT_VOID(${mainReturnCType}, _main_result);`)
      } else {
        lines.push(`    (void)TS_AWAIT(${mainReturnCType}, _main_result);`)
      }
    } else {
      lines.push('    ts_main();')
    }
    lines.push('    return 0;')
    lines.push('}')
  }

  return lines.join('\n')
}
