import docsData from "@/data/docs.json";

/**
 * Docs data layer.
 *
 * Reads from the pre-built docs.json (generated by tools/build-docs-data.ts).
 * No filesystem calls — everything is resolved at build time.
 */

export interface DocPage {
  slug: string;
  title: string;
  category: string;
  content: string;
}

export interface DocCategory {
  name: string;
  label: string;
  pages: DocPage[];
}

const CATEGORY_LABELS: Record<string, { label: string; order: number }> = {
  language: { label: "Language", order: 0 },
  stdlib: { label: "Standard Library", order: 1 },
  runtime: { label: "Runtime", order: 2 },
  tooling: { label: "Tooling", order: 3 },
  guides: { label: "Guides", order: 4 },
};

const pages: DocPage[] = docsData.pages;

export function getAllDocs(): DocPage[] {
  return pages;
}

export function getDocBySlug(slug: string): DocPage | null {
  return pages.find((d) => d.slug === slug) ?? null;
}

export function getCategories(): DocCategory[] {
  const catMap = new Map<string, DocPage[]>();

  for (const doc of pages) {
    if (!catMap.has(doc.category)) catMap.set(doc.category, []);
    catMap.get(doc.category)!.push(doc);
  }

  const categories: DocCategory[] = [];
  for (const [name, catPages] of catMap) {
    categories.push({
      name,
      label: CATEGORY_LABELS[name]?.label ?? name.charAt(0).toUpperCase() + name.slice(1),
      pages: catPages,
    });
  }

  return categories.sort(
    (a, b) =>
      (CATEGORY_LABELS[a.name]?.order ?? 99) -
      (CATEGORY_LABELS[b.name]?.order ?? 99)
  );
}

export function getAllSlugs(): string[] {
  return pages.map((d) => d.slug);
}
