const ROOT = 'examples/native-gui/app-store/assets/'

export const arcadeHeroImage = ROOT + 'hero-arcade.png'

export const iconDredge = ROOT + 'icon-dredge.png'
export const iconFelicity = ROOT + 'icon-felicity.png'
export const iconCult = ROOT + 'icon-cult.png'
export const iconOceanhorn = ROOT + 'icon-oceanhorn.png'
export const iconCozy = ROOT + 'icon-cozy.png'
export const iconSpongeBob = ROOT + 'icon-spongebob.png'
export const iconLego = ROOT + 'icon-lego.png'
export const iconBloons = ROOT + 'icon-bloons.png'
export const iconPacman = ROOT + 'icon-pacman.png'
export const iconNaruto = ROOT + 'icon-naruto.png'
export const iconTMNT = ROOT + 'icon-tmnt.png'
export const iconDreamlight = ROOT + 'icon-dreamlight.png'
export const iconHelloKitty = ROOT + 'icon-hello-kitty.png'
export const iconAngryBirds = ROOT + 'icon-angry-birds.png'
export const iconCooking = ROOT + 'icon-cooking.png'
export const iconRuralLife = ROOT + 'icon-rural-life.png'
export const iconSneaky = ROOT + 'icon-sneaky.png'

export const perkOverview = ROOT + 'perk-overview.png'
export const perkFamily = ROOT + 'perk-family.png'
export const perkNoAds = ROOT + 'perk-no-ads.png'
export const perkNewGames = ROOT + 'perk-new-games.png'

export const developHeroImage = ROOT + 'develop-hero.png'
export const developSpotlightImage = ROOT + 'develop-spotlight.png'
export const playHeroImage = ROOT + 'play-hero.png'
export const playCardOneImage = ROOT + 'play-card-1.png'
export const playCardTwoImage = ROOT + 'play-card-2.png'
export const playCardThreeImage = ROOT + 'play-card-3.png'

export const ruralHeroImage = ROOT + 'rural-hero.png'
export const ruralScreenOneImage = ROOT + 'rural-screen-1.png'
export const ruralScreenTwoImage = ROOT + 'rural-screen-2.png'

export const categoryStrategyImage = ROOT + 'category-strategy.png'
export const categoryFamilyImage = ROOT + 'category-family.png'
export const categoryPuzzleImage = ROOT + 'category-puzzle.png'
export const categorySimulationImage = ROOT + 'category-sim.png'
