export { buildStrictTS } from './build.js'
export { generateC, generateCSingle } from './codegen.js'
export { resolveModules } from './resolver.js'
export { validate } from './validator.js'
export { resolveHostPlatform, type HostPlatform } from './platform.js'
